"""users table

Revision ID: e7980b7fbb5f
Revises: 9fb599940b81
Create Date: 2021-05-31 15:18:09.588604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7980b7fbb5f'
down_revision = '9fb599940b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.drop_index('emial', table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'emial')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('emial', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('emial', 'users', ['emial'], unique=False)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
